<?php
function lyrica_menu() {
    $items['squirrel/lyrics'] = array(
        'type' => MENU_CALLBACK,
        'title' => 'Squirrel Lyrics',
        'page callback' => 'get_itunes',
        'access callback' => TRUE,
    );
    return $items;
}

function get_itunes() {
    drupal_add_css(drupal_get_path('module', 'lyrica') . '/css/style.css', 'module', 'all', TRUE);
    $var = "";
    $var .= '<form id="searchbox" action="">
                <input id="search" type="text" name="term" placeholder="Search Albums, Artists, Lyrics..">
                <input id="submit" type="submit" value="Go">
                </form>';
    if(isset($_REQUEST['term']))
        $term = urlencode($_REQUEST['term']);

    if(empty($term))
        $term = "Celine";
    $json =  file_get_contents('http://itunes.apple.com/search?term='.$term.'&limit=25&media=music&entity=musicArtist,musicTrack,album,mix,song');
    $array = json_decode($json, true);
    $var .= '<div class ="app-folders-container" style="margin-top: 0px;">';
    $var .= '<div class ="<div class ="jaf-row jaf-container">';
    foreach($array['results'] as $value)
    {
       if(isset($value['artworkUrl100']) && $value['artworkUrl100']!=""){
            $var .= '<div class="folder" id='.$value['artistId'] .' style="opacity: 1;">';
            $var .='<a href="#">
                      <img class="app-icon" src='.$value['artworkUrl100'] .'>
                      <p class="album-name">'.$value['collectionName'] .'</p>
                      <p class="artist-name">'.$value['artistName'] .'</p>
                   </a>';
           if(isset($value['previewUrl']) && $value['previewUrl']!=""){
               $var .= '<a href="'.$value['previewUrl'] .'" target="_blank">Play Preview</a>';
           }
           $var .= '</div>';
       }
    }
    $var .= '</div></div>';
    return $var;
}

?>